# Generated by Django 4.2.30 on 2026-06-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.JSONField(blank=True, default=list, verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='主图'),
        ),
    ]
