# Generated by Django 4.2.30 on 2026-06-26 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_gallery_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('stock_in', '入库'), ('stock_out', '出库'), ('transfer', '调拨'), ('gain', '盘盈'), ('loss', '盘亏'), ('order_deduct', '订单扣减'), ('return_in', '退货入库')], max_length=32, verbose_name='变动类型')),
                ('before_quantity', models.IntegerField(verbose_name='变动前库存')),
                ('after_quantity', models.IntegerField(verbose_name='变动后库存')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='变动时间')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='orders.order', verbose_name='关联订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存变动日志',
                'verbose_name_plural': '库存变动日志',
                'db_table': 'products_inventory_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
