# Generated by Django 4.2.30 on 2026-06-26 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='用户名')),
                ('module', models.CharField(max_length=64, verbose_name='模块')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除'), ('other', '其他')], max_length=16, verbose_name='操作类型')),
                ('resource', models.CharField(blank=True, default='', max_length=128, verbose_name='资源')),
                ('resource_id', models.CharField(blank=True, default='', max_length=64, verbose_name='资源ID')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User-Agent')),
                ('request_method', models.CharField(blank=True, default='', max_length=16, verbose_name='请求方法')),
                ('request_path', models.CharField(blank=True, default='', max_length=512, verbose_name='请求路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'audit_operation_log',
                'ordering': ['-id'],
            },
        ),
    ]
