# Generated by Django 4.2.30 on 2026-06-29 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0009_tenant_description'),
        ('products', '0006_product_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='政策名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='政策说明')),
                ('subsidy_type', models.CharField(choices=[('percent', '按比例'), ('fixed', '固定金额')], default='percent', max_length=16, verbose_name='补贴类型')),
                ('subsidy_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='补贴值')),
                ('max_subsidy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单笔最高补贴')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='生效开始')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='生效结束')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '国补政策',
                'verbose_name_plural': '国补政策',
                'db_table': 'subsidy_policy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubsidyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='审核状态')),
                ('subsidy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='补贴金额')),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='驳回原因')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='subsidy.subsidypolicy', verbose_name='适用政策')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_applications', to='products.product', verbose_name='商品')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subsidy_products', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_products', to='tenants.tenant', verbose_name='商家')),
            ],
            options={
                'verbose_name': '国补商品',
                'verbose_name_plural': '国补商品',
                'db_table': 'subsidy_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subsidyproduct',
            constraint=models.UniqueConstraint(fields=('product',), name='uniq_subsidy_product'),
        ),
    ]
