# Generated by Django 4.2.30 on 2026-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0003_filing_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsidyproduct',
            options={'ordering': ['-created_at'], 'verbose_name': '国补商品备案', 'verbose_name_plural': '国补商品备案'},
        ),
        migrations.AlterField(
            model_name='subsidyproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
