# Generated by Django 4.2.30 on 2026-06-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_set_existing_users_not_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='激活令牌'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='激活令牌创建时间'),
        ),
    ]
