# Generated by Django 4.2.30 on 2026-06-26 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_activation_token_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='激活令牌')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='邮件发送时间')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='实际激活时间')),
                ('status', models.CharField(choices=[('pending', '待激活'), ('expired', '已过期'), ('activated', '已激活'), ('failed', '发送失败')], default='pending', max_length=20, verbose_name='状态')),
                ('expired_at', models.DateTimeField(verbose_name='令牌过期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '激活记录',
                'verbose_name_plural': '激活记录',
                'db_table': 'accounts_activation_log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
