# Generated by Django 4.2.30 on 2026-06-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='菜单标题')),
                ('name', models.CharField(blank=True, default='', max_length=64, verbose_name='路由名称')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, default='', max_length=255, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, default='', max_length=64, verbose_name='图标')),
                ('menu_type', models.CharField(choices=[('directory', '目录'), ('menu', '菜单'), ('button', '按钮')], default='menu', max_length=16, verbose_name='菜单类型')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.menu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'rbac_menu',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='权限名称')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='权限编码')),
                ('module', models.CharField(max_length=64, verbose_name='所属模块')),
                ('action', models.CharField(max_length=32, verbose_name='操作类型')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'rbac_permission',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='角色编码')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('menus', models.ManyToManyField(blank=True, related_name='roles', to='rbac.menu', verbose_name='菜单')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='rbac.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'rbac_role',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='rbac.permission', verbose_name='关联权限'),
        ),
    ]
