# Generated by Django 4.2.30 on 2026-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_seller_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancellog',
            options={'ordering': ['-created_at'], 'verbose_name': '订单取消日志', 'verbose_name_plural': '订单取消日志'},
        ),
        migrations.AlterField(
            model_name='cancellog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='cancellog',
            name='operator_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='操作人标识'),
        ),
        migrations.AlterField(
            model_name='cancellog',
            name='operator_type',
            field=models.CharField(choices=[('customer', '用户'), ('merchant', '商户'), ('staff', '平台'), ('system', '系统')], default='system', max_length=16, verbose_name='操作方'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_type',
            field=models.CharField(blank=True, choices=[('user', '用户取消'), ('timeout', '支付超时'), ('merchant', '商户取消'), ('platform', '平台取消'), ('groupbuy', '团购失败')], default='', max_length=16, verbose_name='取消类型'),
        ),
    ]
