# Generated by Django 4.2.30 on 2026-06-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('chat', '0002_conversation_customer_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.tenant', verbose_name='商家'),
        ),
        migrations.AddField(
            model_name='message',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tenants.tenant', verbose_name='商家'),
        ),
    ]
