# Generated by Django 4.2.30 on 2026-06-28 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_message_senders(apps, schema_editor):
    Message = apps.get_model('chat', 'Message')
    for message in Message.objects.all().iterator():
        if message.is_staff:
            message.sender_type = 'staff'
            message.sender_staff_id = message.sender_id
            message.sender_user_id = None
        else:
            message.sender_type = 'user'
            message.sender_user_id = message.sender_customer_id
            message.sender_staff_id = None
        message.save(update_fields=['sender_type', 'sender_staff_id', 'sender_user_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('customers', '0006_rename_customers_s_phone_s_6f8d0d_idx_customers_s_phone_75dbe1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_conversation_tenant_message_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='user_unread_count',
            new_name='unread_count_user',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='staff_unread_count',
            new_name='unread_count_staff',
        ),
        migrations.AddField(
            model_name='message',
            name='is_sensitive',
            field=models.BooleanField(default=False, verbose_name='是否敏感信息'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_staff',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sent_messages',
                to=settings.AUTH_USER_MODEL,
                verbose_name='客服发送者',
            ),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(
                choices=[('user', '用户'), ('staff', '客服'), ('system', '系统')],
                default='user',
                max_length=10,
                verbose_name='发送者类型',
            ),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sent_messages',
                to='customers.customer',
                verbose_name='用户发送者',
            ),
        ),
        migrations.RunPython(migrate_message_senders, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='message',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_customer',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='conversations',
                to='tenants.tenant',
                verbose_name='所属商家',
            ),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', ['pending', 'active'])),
                fields=('tenant', 'user'),
                name='chat_unique_active_conversation_per_tenant_user',
            ),
        ),
    ]
