# Generated by Django 4.2.30 on 2026-06-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_triangular_chat_routing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='unread_count_staff',
            field=models.PositiveIntegerField(default=0, verbose_name='客服端未读'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='unread_count_user',
            field=models.PositiveIntegerField(default=0, verbose_name='用户端未读'),
        ),
    ]
