# Generated by Django 4.2.30 on 2026-06-29 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_alter_cancellog_options_alter_cancellog_created_at_and_more'),
        ('chat', '0007_dispute_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='orders.order', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解决时间'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_complaints', to=settings.AUTH_USER_MODEL, verbose_name='平台处理人'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
