# Generated by Django 4.2.30 on 2026-06-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_points', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sellerpointstransaction',
            new_name='seller_poin_tenant__c7a1c3_idx',
            old_name='seller_pts_tx_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerpointstransaction',
            new_name='seller_poin_custome_ebc337_idx',
            old_name='seller_pts_tx_cust_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerpointstransaction',
            new_name='seller_poin_source__3b1dfb_idx',
            old_name='seller_pts_tx_src_idx',
        ),
    ]
