# Generated by Django 4.2.30 on 2026-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, default='', verbose_name='配置值')),
                ('value_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('boolean', '布尔'), ('file', '文件')], default='string', max_length=16, verbose_name='值类型')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_setting',
                'ordering': ['key'],
            },
        ),
    ]
