# Generated by Django 4.2.30 on 2026-06-26 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_inventorylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeckillActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='活动名称')),
                ('seckill_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='秒杀价')),
                ('seckill_stock', models.PositiveIntegerField(verbose_name='秒杀库存')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='每人限购')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('warmup_time', models.DateTimeField(blank=True, null=True, verbose_name='预热时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '审核中'), ('running', '进行中'), ('ended', '已结束'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='驳回原因')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_seckills', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seckills', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('products', models.ManyToManyField(related_name='seckill_activities', to='products.product', verbose_name='参与商品')),
            ],
            options={
                'verbose_name': '秒杀活动',
                'verbose_name_plural': '秒杀活动',
                'db_table': 'promotion_seckill_activity',
                'ordering': ['-created_at'],
            },
        ),
    ]
