# Generated by Django 4.2.30 on 2026-06-26 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_inventorylog'),
        ('orders', '0002_order_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='优惠券名称')),
                ('coupon_type', models.CharField(choices=[('fixed', '满减券'), ('discount', '折扣券'), ('free', '无门槛券')], default='fixed', max_length=20, verbose_name='类型')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='满减金额')),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='折扣率')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大折扣金额')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='使用门槛')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='发放总量')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='每人限领')),
                ('applicable_scope', models.CharField(choices=[('all', '全部商品'), ('category', '指定分类'), ('product', '指定商品')], default='all', max_length=20, verbose_name='适用范围')),
                ('valid_type', models.CharField(choices=[('fixed', '固定时间'), ('after_receive', '领取后有效')], default='fixed', max_length=20, verbose_name='有效期类型')),
                ('valid_start', models.DateTimeField(blank=True, null=True, verbose_name='有效开始')),
                ('valid_end', models.DateTimeField(blank=True, null=True, verbose_name='有效结束')),
                ('valid_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='领取后有效天数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('expired', '已过期'), ('disabled', '已停用')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicable_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='products.category', verbose_name='适用分类')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupons', to='products.product', verbose_name='适用商品')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'promotion_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupBuyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='活动名称')),
                ('group_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='团购价')),
                ('group_size', models.PositiveIntegerField(default=3, verbose_name='成团人数')),
                ('stock', models.PositiveIntegerField(verbose_name='活动库存')),
                ('per_user_limit', models.PositiveIntegerField(default=5, verbose_name='每人限购')),
                ('group_valid_hours', models.PositiveIntegerField(default=24, verbose_name='拼团有效期(小时)')),
                ('auto_group', models.BooleanField(default=False, verbose_name='虚拟成团')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '审核中'), ('running', '进行中'), ('ended', '已结束'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='驳回原因')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_groupbuys', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groupbuys', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupbuy_activities', to='products.product', verbose_name='拼团商品')),
            ],
            options={
                'verbose_name': '团购活动',
                'verbose_name_plural': '团购活动',
                'db_table': 'promotion_groupbuy_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='券码')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('expired_at', models.DateTimeField(verbose_name='过期时间')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=20, verbose_name='状态')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='promotion.coupon', verbose_name='优惠券')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to='orders.order', verbose_name='使用订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'promotion_user_coupon',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '拼团中'), ('success', '已成团'), ('failed', '拼团失败')], default='pending', max_length=20, verbose_name='状态')),
                ('expired_at', models.DateTimeField(verbose_name='拼团截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_orders', to='promotion.groupbuyactivity', verbose_name='团购活动')),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_group_orders', to=settings.AUTH_USER_MODEL, verbose_name='团长')),
                ('members', models.ManyToManyField(blank=True, related_name='member_group_orders', to=settings.AUTH_USER_MODEL, verbose_name='团员')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_orders', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '拼团订单',
                'verbose_name_plural': '拼团订单',
                'db_table': 'promotion_group_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
