# Generated by Django 4.2.30 on 2026-06-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('promotion', '0002_coupon_groupbuyactivity_usercoupon_grouporder'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='tenants.tenant', verbose_name='商家'),
        ),
        migrations.AddField(
            model_name='groupbuyactivity',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupbuy_activities', to='tenants.tenant', verbose_name='商家'),
        ),
        migrations.AddField(
            model_name='seckillactivity',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seckill_activities', to='tenants.tenant', verbose_name='商家'),
        ),
    ]
