# Generated by Django 4.2.30 on 2026-06-30 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('subsidy', '国补申请'), ('closure', '店铺注销'), ('tenant_change', '商户信息变更'), ('product', '商品审核'), ('coupon', '优惠券审核'), ('seckill', '秒杀活动'), ('groupbuy', '团购活动'), ('refund', '退款审核'), ('tag', '标签参与'), ('tenant', '商户入驻')], db_index=True, max_length=50, verbose_name='审核类型')),
                ('business_type', models.CharField(db_index=True, max_length=50, verbose_name='业务类型')),
                ('business_id', models.PositiveIntegerField(db_index=True, verbose_name='业务ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='摘要')),
                ('application_data', models.JSONField(blank=True, default=dict, verbose_name='申请数据')),
                ('action_url', models.CharField(blank=True, default='', max_length=500, verbose_name='跳转链接')),
                ('applicant_type', models.CharField(choices=[('tenant', '商户'), ('staff', '员工')], max_length=20, verbose_name='申请人类型')),
                ('applicant_id', models.PositiveIntegerField(verbose_name='申请人ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='驳回原因')),
                ('review_remark', models.TextField(blank=True, default='', verbose_name='审核备注')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], db_index=True, default='normal', max_length=20, verbose_name='优先级')),
                ('timeout_at', models.DateTimeField(blank=True, null=True, verbose_name='超时时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '统一审核',
                'verbose_name_plural': '统一审核',
                'db_table': 'approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', '提交'), ('approve', '通过'), ('reject', '驳回'), ('cancel', '取消')], max_length=20, verbose_name='操作')),
                ('operator_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('operator_name', models.CharField(blank=True, default='', max_length=100, verbose_name='操作人')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='approval.approval', verbose_name='审核单')),
            ],
            options={
                'verbose_name': '审核日志',
                'verbose_name_plural': '审核日志',
                'db_table': 'approval_log',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['status', 'approval_type'], name='approval_status_c0ef49_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['business_type', 'business_id'], name='approval_busines_6e16aa_idx'),
        ),
    ]
