# Generated by Django 4.2.30 on 2026-06-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, default='', max_length=128, verbose_name='邮箱')),
                ('level', models.CharField(choices=[('normal', '普通会员'), ('silver', '白银会员'), ('gold', '黄金会员'), ('platinum', '铂金会员')], default='normal', max_length=16, verbose_name='会员等级')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='积分')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customers_customer',
                'ordering': ['-id'],
            },
        ),
    ]
