# Generated by Django 4.2.30 on 2026-06-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('customers', '0005_sms_scene_login'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='smsverificationcode',
            new_name='customers_s_phone_75dbe1_idx',
            old_name='customers_s_phone_s_6f8d0d_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant', verbose_name='商家'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='手机号'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='customers_customer_tenant_phone_uniq'),
        ),
    ]
