"""Seller portal URL routes."""

from django.urls import path

from complaints.seller_views import (
    SellerComplaintDetailView,
    SellerComplaintListView,
    SellerComplaintReplyView,
    SellerComplaintSummaryView,
)
from feedback.seller_views import (
    SellerFeedbackDetailView,
    SellerFeedbackListView,
    SellerFeedbackReplyView,
    SellerFeedbackSummaryView,
)
from promotion.seller_views import (
    SellerCouponDetailView,
    SellerCouponDisableView,
    SellerCouponListView,
    SellerCouponPublishView,
    SellerGroupBuyCancelView,
    SellerGroupBuyDetailView,
    SellerGroupBuyListView,
    SellerGroupBuySubmitView,
    SellerGroupOrderListView,
    SellerSeckillCancelView,
    SellerSeckillDetailView,
    SellerSeckillListView,
    SellerSeckillSubmitView,
)
from seller_points.seller_views import (
    SellerPointsAccountListView,
    SellerPointsAdjustView,
    SellerPointsRuleView,
    SellerPointsTransactionListView,
)
from tag_system.seller_views import (
    SellerProductTagConfigListView,
    SellerTagConfigView,
    SellerTagListView,
)
from subsidy.seller_views import (
    SellerSubsidyAvailableProductsView,
    SellerSubsidyExportView,
    SellerSubsidyOrderCodesView,
    SellerSubsidyOrderListView,
    SellerSubsidyProductListView,
)
from tenants.seller_views import (
    SellerAppealChatMessageView,
    SellerAppealChatOpenView,
    SellerAppealCreateView,
    SellerAppealDetailView,
    SellerAppealMineView,
    SellerAppealReplyView,
    SellerBrandListView,
    SellerCategoryListView,
    SellerCustomerDetailView,
    SellerCustomerListView,
    SellerDashboardView,
    SellerExpressCompaniesView,
    SellerInboxListView,
    SellerInboxReadView,
    SellerInboxReadAllView,
    SellerInboxSummaryView,
    SellerLoginView,
    SellerOrderCancelReviewView,
    SellerOrderCancelView,
    SellerOrderDetailView,
    SellerOrderListView,
    SellerOrderShipView,
    SellerProductDetailView,
    SellerProductListView,
    SellerProductToggleView,
    SellerProfileView,
    SellerStaffCreateView,
    SellerStaffDeleteView,
    SellerStaffListView,
    SellerTenantApplyCheckView,
    SellerTenantApplyView,
    SellerTenantCloseView,
    SellerTenantProfileView,
)

urlpatterns = [
    path('seller/auth/login/', SellerLoginView.as_view(), name='seller-login'),
    path('seller/auth/profile/', SellerProfileView.as_view(), name='seller-profile'),
    path('seller/dashboard/', SellerDashboardView.as_view(), name='seller-dashboard'),
    path('seller/products/', SellerProductListView.as_view(), name='seller-products'),
    path('seller/products/<int:pk>/', SellerProductDetailView.as_view(), name='seller-product-detail'),
    path('seller/products/<int:pk>/toggle/', SellerProductToggleView.as_view(), name='seller-product-toggle'),
    path('seller/feedbacks/summary/', SellerFeedbackSummaryView.as_view(), name='seller-feedback-summary'),
    path('seller/feedbacks/', SellerFeedbackListView.as_view(), name='seller-feedbacks'),
    path('seller/feedbacks/<int:pk>/', SellerFeedbackDetailView.as_view(), name='seller-feedback-detail'),
    path('seller/feedbacks/<int:pk>/reply/', SellerFeedbackReplyView.as_view(), name='seller-feedback-reply'),
    path('seller/categories/', SellerCategoryListView.as_view(), name='seller-categories'),
    path('seller/brands/', SellerBrandListView.as_view(), name='seller-brands'),
    path('seller/seckills/', SellerSeckillListView.as_view(), name='seller-seckills'),
    path('seller/seckills/<int:pk>/', SellerSeckillDetailView.as_view(), name='seller-seckill-detail'),
    path('seller/seckills/<int:pk>/submit/', SellerSeckillSubmitView.as_view(), name='seller-seckill-submit'),
    path('seller/seckills/<int:pk>/cancel/', SellerSeckillCancelView.as_view(), name='seller-seckill-cancel'),
    path('seller/groupbuys/', SellerGroupBuyListView.as_view(), name='seller-groupbuys'),
    path('seller/groupbuys/<int:pk>/', SellerGroupBuyDetailView.as_view(), name='seller-groupbuy-detail'),
    path('seller/groupbuys/<int:pk>/submit/', SellerGroupBuySubmitView.as_view(), name='seller-groupbuy-submit'),
    path('seller/groupbuys/<int:pk>/cancel/', SellerGroupBuyCancelView.as_view(), name='seller-groupbuy-cancel'),
    path('seller/groupbuys/<int:pk>/group-orders/', SellerGroupOrderListView.as_view(), name='seller-group-orders'),
    path('seller/coupons/', SellerCouponListView.as_view(), name='seller-coupons'),
    path('seller/coupons/<int:pk>/', SellerCouponDetailView.as_view(), name='seller-coupon-detail'),
    path('seller/coupons/<int:pk>/publish/', SellerCouponPublishView.as_view(), name='seller-coupon-publish'),
    path('seller/coupons/<int:pk>/disable/', SellerCouponDisableView.as_view(), name='seller-coupon-disable'),
    path('seller/orders/', SellerOrderListView.as_view(), name='seller-orders'),
    path('seller/orders/<int:pk>/', SellerOrderDetailView.as_view(), name='seller-order-detail'),
    path('seller/orders/<int:pk>/ship/', SellerOrderShipView.as_view(), name='seller-order-ship'),
    path('seller/orders/<int:pk>/cancel/', SellerOrderCancelView.as_view(), name='seller-order-cancel'),
    path('seller/orders/<int:pk>/cancel-review/', SellerOrderCancelReviewView.as_view(), name='seller-order-cancel-review'),
    path('seller/complaints/summary/', SellerComplaintSummaryView.as_view(), name='seller-complaint-summary'),
    path('seller/complaints/', SellerComplaintListView.as_view(), name='seller-complaints'),
    path('seller/complaints/<int:pk>/', SellerComplaintDetailView.as_view(), name='seller-complaint-detail'),
    path('seller/complaints/<int:pk>/reply/', SellerComplaintReplyView.as_view(), name='seller-complaint-reply'),
    path('seller/express-companies/', SellerExpressCompaniesView.as_view(), name='seller-express-companies'),
    path('seller/customers/', SellerCustomerListView.as_view(), name='seller-customers'),
    path('seller/customers/<int:pk>/', SellerCustomerDetailView.as_view(), name='seller-customer-detail'),
    path('seller/staff/', SellerStaffListView.as_view(), name='seller-staff-list'),
    path('seller/staff/create/', SellerStaffCreateView.as_view(), name='seller-staff-create'),
    path('seller/staff/<int:pk>/', SellerStaffDeleteView.as_view(), name='seller-staff-delete'),
    path('seller/appeals/', SellerAppealCreateView.as_view(), name='seller-appeal-create'),
    path('seller/appeals/chat/open/', SellerAppealChatOpenView.as_view(), name='seller-appeal-chat-open'),
    path('seller/appeals/chat/messages/', SellerAppealChatMessageView.as_view(), name='seller-appeal-chat-messages'),
    path('seller/inbox/summary/', SellerInboxSummaryView.as_view(), name='seller-inbox-summary'),
    path('seller/inbox/', SellerInboxListView.as_view(), name='seller-inbox-list'),
    path('seller/profile/', SellerTenantProfileView.as_view(), name='seller-tenant-profile'),
    path('seller/profile/close/', SellerTenantCloseView.as_view(), name='seller-tenant-close'),
    path('seller/inbox/<int:pk>/read/', SellerInboxReadView.as_view(), name='seller-inbox-read'),
    path('seller/inbox/read-all/', SellerInboxReadAllView.as_view(), name='seller-inbox-read-all'),
    path('seller/appeals/mine/', SellerAppealMineView.as_view(), name='seller-appeals-mine'),
    path('seller/appeals/<int:pk>/', SellerAppealDetailView.as_view(), name='seller-appeal-detail'),
    path('seller/appeals/<int:pk>/reply/', SellerAppealReplyView.as_view(), name='seller-appeal-reply'),
    path('seller/apply/check/', SellerTenantApplyCheckView.as_view(), name='seller-apply-check'),
    path('seller/apply/', SellerTenantApplyView.as_view(), name='seller-apply'),
    path('seller/subsidy/products/', SellerSubsidyProductListView.as_view(), name='seller-subsidy-products'),
    path('seller/subsidy/available-products/', SellerSubsidyAvailableProductsView.as_view(), name='seller-subsidy-available'),
    path('seller/subsidy/filings/<int:pk>/export/', SellerSubsidyExportView.as_view(), name='seller-subsidy-export'),
    path('seller/subsidy/orders/', SellerSubsidyOrderListView.as_view(), name='seller-subsidy-orders'),
    path('seller/subsidy/orders/<int:pk>/codes/', SellerSubsidyOrderCodesView.as_view(), name='seller-subsidy-order-codes'),
    path('seller/points/rule/', SellerPointsRuleView.as_view(), name='seller-points-rule'),
    path('seller/points/accounts/', SellerPointsAccountListView.as_view(), name='seller-points-accounts'),
    path('seller/points/transactions/', SellerPointsTransactionListView.as_view(), name='seller-points-transactions'),
    path('seller/points/adjust/', SellerPointsAdjustView.as_view(), name='seller-points-adjust'),
    path('seller/tags/', SellerTagListView.as_view(), name='seller-tag-list'),
    path('seller/tag-configs/', SellerTagConfigView.as_view(), name='seller-tag-config'),
    path('seller/product-tag-configs/', SellerProductTagConfigListView.as_view(), name='seller-product-tag-config'),
]
