# Generated by Django 4.2.30 on 2026-06-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('customers', '0005_sms_scene_login'),
        ('cart', '0002_cart_customer_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='tenants.tenant', verbose_name='商家'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='customers.customer', verbose_name='商城用户'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'tenant')},
        ),
    ]
