# Generated by Django 4.2.30 on 2026-06-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rename_customers_s_phone_s_6f8d0d_idx_customers_s_phone_75dbe1_idx_and_more'),
        ('tenants', '0001_initial'),
        ('points', '0003_backfill_points_accounts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pointstransaction',
            new_name='points_tran_custome_05059b_idx',
            old_name='points_tran_custome_6f0d0d_idx',
        ),
        migrations.RenameIndex(
            model_name='pointstransaction',
            new_name='points_tran_source_ce12e9_idx',
            old_name='points_tran_source_0d8f0a_idx',
        ),
        migrations.AddField(
            model_name='pointsaccount',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_accounts', to='tenants.tenant', verbose_name='商家'),
        ),
        migrations.AlterField(
            model_name='pointsaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_accounts', to='customers.customer', verbose_name='会员'),
        ),
        migrations.AlterUniqueTogether(
            name='pointsaccount',
            unique_together={('customer', 'tenant')},
        ),
    ]
