# Generated by Django 4.2.30 on 2026-06-28 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商家名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商家编码')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='Logo')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('address', models.TextField(blank=True, null=True, verbose_name='商家地址')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('active', '已入驻'), ('suspended', '已暂停'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='入驻状态')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='商家配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tenants', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家管理',
                'db_table': 'tenants_tenant',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TenantStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '商家管理员'), ('manager', '经理'), ('staff', '普通员工')], default='staff', max_length=20, verbose_name='员工角色')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='自定义权限')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='tenants.tenant', verbose_name='商家')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_staffs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商家员工',
                'verbose_name_plural': '商家员工',
                'db_table': 'tenants_staff',
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
