# Generated by Django 4.2.30 on 2026-06-28 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0007_tenant_change_review_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_license',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='营业执照'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_person',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='法人姓名'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pending_business_license',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='待审核执照'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pending_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='待审核邮箱'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pending_contact_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='待审核联系人'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pending_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='待审核电话'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pending_legal_person',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='待审核法人'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pending_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='待审核名称'),
        ),
        migrations.CreateModel(
            name='TenantChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='变更字段')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='原值')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='新值')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], db_index=True, default='pending', max_length=20, verbose_name='审核状态')),
                ('operator_type', models.CharField(choices=[('tenant', '商户'), ('platform', '平台')], default='tenant', max_length=20, verbose_name='操作方')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_remark', models.CharField(blank=True, default='', max_length=500, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_change_logs', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tenant_changes', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='tenants.tenant', verbose_name='商家')),
            ],
            options={
                'verbose_name': '商户变更记录',
                'verbose_name_plural': '商户变更记录',
                'db_table': 'tenants_change_log',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='tenants_cha_tenant__da5d17_idx'), models.Index(fields=['status', '-created_at'], name='tenants_cha_status_e0f61a_idx')],
            },
        ),
    ]
