# Generated by Django 4.2.30 on 2026-06-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('customer', '客户'), ('tenant', '商户'), ('staff', '后台员工')], db_index=True, max_length=20)),
                ('recipient_id', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('order', '订单'), ('refund', '售后'), ('inventory', '库存'), ('complaint', '投诉'), ('tenant', '商户'), ('chat', '客服'), ('points', '积分'), ('system', '系统')], db_index=True, max_length=50)),
                ('related_url', models.CharField(blank=True, default='', max_length=500)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_type', 'recipient_id', 'is_read'], name='notificatio_recipie_e611ec_idx')],
            },
        ),
    ]
