# Generated by Django 4.2.30 on 2026-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', '订单'), ('refund', '售后'), ('inventory', '库存'), ('complaint', '投诉'), ('tenant', '商户'), ('chat', '客服'), ('points', '积分'), ('system', '系统'), ('approval', '审核')], db_index=True, max_length=50),
        ),
    ]
