# Generated by Django 4.2.30 on 2026-06-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='need_popup',
            field=models.BooleanField(default=False, verbose_name='需要弹窗'),
        ),
        migrations.AddField(
            model_name='notification',
            name='need_sound',
            field=models.BooleanField(default=False, verbose_name='需要声音'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', '订单'), ('order_new', '新订单'), ('order_paid', '订单已支付'), ('order_shipped', '订单已发货'), ('order_completed', '订单已完成'), ('order_cancelled', '订单已取消'), ('refund', '售后'), ('refund_applied', '售后申请'), ('refund_reviewed', '售后审核'), ('inventory', '库存'), ('stock_warning', '库存预警'), ('complaint', '投诉'), ('tenant', '商户'), ('tenant_apply', '入驻申请'), ('chat', '客服'), ('points', '积分'), ('system', '系统'), ('approval', '审核'), ('approval_pending', '待审核'), ('approval_result', '审核结果'), ('subsidy_applied', '国补申请'), ('closure_applied', '注销申请')], db_index=True, max_length=50),
        ),
    ]
